<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<div class="newsletter wrapper">
    <div class="newsletter-block">
        <div class="title">
            <h2><?= $block->escapeHtml(__('keep updated')) ?></h2>
            <p><?= $block->escapeHtml(__('Sign up for our newletter to recevie updates an exlusive offers')) ?></p>
        </div>
        <div class="content">
            <form class="form subscribe"
                novalidate
                action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
                method="post"
                data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                id="newsletter-validate-detail">
                <div class="field newsletter">
                    <div class="control">
                        <label for="newsletter">
                            <input name="email" type="email" id="newsletter"
                                   placeholder="<?= $block->escapeHtml(__('Enter your email')) ?>"
                                   data-mage-init='{"mage/trim-input":{}}'
                                   data-validate="{required:true, 'validate-email':true}"
                            />
                        </label>
                    </div>
                </div>
                <div class="actions">
                    <button class="action subscribe primary"
                            title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                            type="submit"
                            aria-label="Subscribe">
                        <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "newsletter-validate-detail"
            }
        }
    }
</script>
