<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\PostList\Item
 */
?>
<?php
$_post = $block->getPost();
$_postUrl = $block->escapeUrl($_post->getPostUrl());
$_postName = $block->escapeHtml($_post->getTitle());
?>
<li class="post-holder post-holder-<?= (int)$_post->getId() ?>">


    <div class="post-content">
        <div class="post-description clearfix">
            <?php $featuredImage = $_post->getFeaturedListImage() ?: $_post->getFeaturedImage(); ?>
            <?php if ($featuredImage) { ?>
                <?php
                $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                if (!$featuredImgAlt) {
                    $featuredImgAlt = $_postName;
                }
                ?>
                <div class="post-ftimg-hld">
                    <a href="<?= /*@noEscape*/ $_postUrl ?>"
                       title="<?= /*@noEscape*/ $_postName ?>">
                        <img src="<?= $block->escapeUrl($featuredImage) ?>"
                             alt="<?= $block->escapeHtml($featuredImgAlt) ?>" />
                    </a>
                </div>
            <?php } ?>

            <div class="post-title-holder">
                <div class="post-title">
                    <a class="post-item-link"
                       href="<?= /*@noEscape*/ $_postUrl ?>">
                        <?= /*@noEscape*/ $_postName ?>
                    </a>
                </div>
            </div>
            <?php if ($_post->isPublishDateEnabled()) { ?>
                <div class="item post-posed-date">
                    <span class="value"><?= $block->escapeHtml($_post->getPublishDate('d-M-Y')) ?></span>
                </div>
            <?php } ?>

            <div class="post-text-hld clearfix">
                <?= /*@noEscape*/ $block->getShorContent() ?>
            </div>
        </div>
    </div>
    <div class="post-footer">

    </div>
</li>
